from .optimal_transport import bures_distance_matrix2
from .optimal_transport import wasserstein_type_distance
from .optimal_transport import my_symmetric_sqrt
from .optimal_transport import my_bures_log
from .optimal_transport import wasserstein_type_barycenter